
def build_trigger_bp_rules(
    TemplateRule,
    *,
    regex_match,
    bp_debuff_builder,
    conditional_bp_debuff_builder,
    bp_sum_limit_remove_builder,
    bp_sum_limit_remove_dynamic_energy_builder,
    bp_bounce_to_hand_builder,
    bp_remove_from_match_builder_factory,
):
    return (
        TemplateRule(
            name="trigger.bp_debuff",
            event_filter=("ON_ENTER", "MAIN_ACTIVATE"),
            matcher=regex_match(r"BP(\d+)以上の相手のフロントLのキャラを1枚選び、このターン中、BP-(\d+)。"),
            builder=bp_debuff_builder,
            priority=204,
            template_metadata={"family": "BP_DEBUFF", "variant": "bp_gte_target_temp_debuff"},
        ),
        TemplateRule(
            name="trigger.conditional_bp_debuff",
            event_filter=("ON_ENTER", "MAIN_ACTIVATE"),
            matcher=regex_match(r"自分の場に〈(.+)〉がある場合、BP(\d+)以上の相手のフロントLのキャラを1枚まで選び、このターン中、BP-(\d+)。"),
            builder=conditional_bp_debuff_builder,
            priority=204,
            template_metadata={"family": "BP_DEBUFF", "variant": "conditional_bp_gte_target_temp_debuff"},
        ),
        TemplateRule(
            name="trigger.bp_sum_limit_remove",
            event_filter=("ON_ENTER", "ON_ATTACK", "ON_BLOCK", "ON_LIFE_TRIGGER", "ON_LEAVE"),
            matcher=regex_match(r"BPの合計が(\d+)以下になるように相手のフロントLのキャラを(\d+)枚まで選び、退場させる。"),
            builder=bp_sum_limit_remove_builder,
            priority=135,
            template_metadata={"family": "BP_SUM_LIMIT_REMOVE", "variant": "bp_sum_limit_remove_optional"},
        ),
        TemplateRule(
            name="trigger.bp_sum_limit_remove.dynamic_energy_line",
            event_filter=("ON_ENTER", "ON_ATTACK", "ON_BLOCK", "ON_LIFE_TRIGGER", "ON_LEAVE"),
            matcher=regex_match(r"BPの合計が自分のエナジーラインのカード枚数×(\d+)以下になるように相手のフロントLのキャラを(\d+)枚まで選び、退場させる。"),
            builder=bp_sum_limit_remove_dynamic_energy_builder,
            priority=136,
            template_metadata={"family": "BP_SUM_LIMIT_REMOVE", "variant": "bp_sum_limit_remove_dynamic_energy_line"},
        ),
        TemplateRule(
            name="trigger.bp_bounce_to_hand",
            event_filter=("ON_ENTER", "ON_ATTACK", "ON_BLOCK", "ON_LIFE_TRIGGER", "ON_LEAVE"),
            matcher=regex_match(r"BP(\d+)以下の相手のフロントLのキャラを(\d+)枚選び、手札に戻す。"),
            builder=bp_bounce_to_hand_builder,
            priority=134,
            template_metadata={"family": "BP_FILTER_BOUNCE", "variant": "bp_threshold_return_to_hand_required"},
        ),
        TemplateRule(
            name="trigger.bp_remove.required",
            event_filter=("ON_ENTER", "ON_ATTACK", "ON_BLOCK", "ON_LIFE_TRIGGER", "ON_LEAVE"),
            matcher=regex_match(r"BP(\d+)以下の相手のフロントLのキャラを1枚選び、退場させる。"),
            builder=bp_remove_from_match_builder_factory(min_count=1, max_count=1),
            priority=120,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_threshold_remove_required"},
        ),
        TemplateRule(
            name="trigger.bp_remove.optional",
            event_filter=("ON_ENTER", "ON_ATTACK", "ON_BLOCK", "ON_LIFE_TRIGGER", "ON_LEAVE"),
            matcher=regex_match(r"BP(\d+)以下の相手のフロントLのキャラを1枚まで選び、退場させる。"),
            builder=bp_remove_from_match_builder_factory(min_count=0, max_count=1),
            priority=110,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_threshold_remove_optional"},
        ),
    )


def build_event_bp_rules(
    TemplateRule,
    *,
    regex_match,
    exact_text_match,
    conditional_rest_or_remove_builder,
    bp_remove_then_choice_branch_builder,
    bp_remove_then_optional_pay_ap_add_outside_name_contains_builder,
    conditional_bp_replace_marker_builder,
    bp_remove_dynamic_name_gate_energy_lte_count_builder,
    bp_remove_from_match_builder_factory,
    bp_remove_dynamic_name_gate_builder,
    bp_remove_dynamic_name_contains_gate_builder,
    bp_remove_to_removed_dynamic_name_gate_builder,
    bp_remove_with_requirements_builder_factory,
    bp_sum_limit_remove_dynamic_energy_builder,
    conditional_value_provider,
    fixed_value_provider,
):
    return (
        TemplateRule(
            name="event.conditional_rest_or_remove",
            event_filter="ON_PLAY",
            matcher=regex_match(r"BP(\d+)以下の相手のフロントLのキャラを1枚選び、『レストにする。それは次の1回アクティブにならない』。自分の場に〈(.+)〉がある場合、『退場させる』に代わる。"),
            builder=conditional_rest_or_remove_builder,
            priority=202,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "remove_or_rest_lock_by_name_gate"},
        ),
        TemplateRule(
            name="event.bp_remove_then_choice_branch",
            event_filter="ON_PLAY",
            matcher=regex_match(r"『?BP(\d+)以下』?の相手のフロントLのキャラを1枚選び、退場させる。以下から1つ選ぶ。"),
            builder=bp_remove_then_choice_branch_builder,
            priority=202,
            template_metadata={"family": "MULTI_BRANCH_CHOICE", "variant": "bp_remove_then_choice_branch"},
        ),
        TemplateRule(
            name="event.bp_remove_then_optional_pay_ap_add_outside_name_contains",
            event_filter="ON_PLAY",
            matcher=regex_match(r"BP(\d+)以下の相手のフロントLのキャラを1枚選び、退場させる。自分のフロントLにカード名に「(.+)」を含むキャラとカード名に「(.+)」を含むキャラがある場合、APを(\d+)支払ってもよい。そうした場合、自分の場外からカード名に「(.+)」か「(.+)」を含むキャラカードを1枚まで手札に加える。"),
            builder=bp_remove_then_optional_pay_ap_add_outside_name_contains_builder,
            priority=202,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_remove_then_optional_pay_ap_add_outside_name_contains"},
        ),
        TemplateRule(
            name="event.conditional_bp_replace_marker",
            event_filter="ON_PLAY",
            matcher=regex_match(r"・?自分の場に〈(.+)〉がある場合、『BP(\d+)以下』に代わる。"),
            builder=conditional_bp_replace_marker_builder,
            priority=202,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "conditional_bp_replace_marker"},
        ),
        TemplateRule(
            name="event.bp_remove_dynamic_name_gate_energy_lte_count",
            event_filter="ON_PLAY",
            matcher=regex_match(r"『?BP(\d+)』?以下の相手のフロントLのキャラを1枚選び、退場させる。自分の場に〈(.+)〉がある場合、自分のフロントLの必要エナジーが(\d+)以下のキャラ1枚につき、この効果で選べるキャラのBPの範囲\+(\d+)。"),
            builder=bp_remove_dynamic_name_gate_energy_lte_count_builder,
            priority=202,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_remove_dynamic_name_gate_energy_lte_count"},
        ),
        TemplateRule(
            name="event.bp_remove.required",
            event_filter="ON_PLAY",
            matcher=regex_match(r"・?『?BP(\d+)以下』?の相手のフロントLのキャラを1枚選び、退場させる。"),
            builder=bp_remove_from_match_builder_factory(min_count=1, max_count=1, kind="TRIGGERED"),
            priority=120,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_threshold_remove_required"},
        ),
        TemplateRule(
            name="event.bp_remove.optional",
            event_filter="ON_PLAY",
            matcher=regex_match(r"BP(\d+)以下の相手のフロントLのキャラを1枚まで選び、退場させる。"),
            builder=bp_remove_from_match_builder_factory(min_count=0, max_count=1, kind="TRIGGERED"),
            priority=110,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_threshold_remove_optional"},
        ),
        TemplateRule(
            name="event.bp_remove.dynamic_name_gate",
            event_filter="ON_PLAY",
            matcher=regex_match(r"『?BP(\d+)以下』?の相手のフロントLのキャラを1枚選び、退場させる。自分の場に〈(.+)〉がある場合、『?BP(\d+)以下』?に代わる。"),
            builder=bp_remove_dynamic_name_gate_builder,
            priority=125,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_threshold_remove_dynamic_name_gate"},
        ),
        TemplateRule(
            name="event.bp_remove.dynamic_name_contains_gate",
            event_filter="ON_PLAY",
            matcher=regex_match(r"『?BP(\d+)以下』?の相手のフロントLのキャラを1枚選び、退場させる。自分の場にカード名に「(.+)」を含むキャラがある場合、『?BP(\d+)以下』?に代わる。"),
            builder=bp_remove_dynamic_name_contains_gate_builder,
            priority=126,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_threshold_remove_dynamic_name_contains_gate"},
        ),
        TemplateRule(
            name="event.bp_remove_to_removed.dynamic_name_gate",
            event_filter="ON_PLAY",
            matcher=regex_match(r"『?BP(\d+)以下』?の相手のフロントLのキャラを1枚選び、リムーブエリアに置く。自分の場に〈(.+)〉がある場合、『?BP(\d+)以下』?に代わる。"),
            builder=bp_remove_to_removed_dynamic_name_gate_builder,
            priority=127,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_threshold_remove_to_removed_dynamic_name_gate"},
        ),
        TemplateRule(
            name="event.bp_remove.dynamic_sayaka_life",
            event_filter="ON_PLAY",
            matcher=exact_text_match("『BP3000以下』の相手のフロントLのキャラを1枚選び、退場させる。自分の場に〈美樹 さやか〉があり、自分のライフが5以下の場合、『BP5000以下』に代わる。"),
            builder=bp_remove_with_requirements_builder_factory(
                [
                    {
                        "type": "CARD_BP_LTE_DYNAMIC",
                        "value_provider": conditional_value_provider(
                            fixed_value_provider(3000),
                            [
                                {"type": "CONTROLLER_HAS_NAME_IN_FIELD", "value": "美樹 さやか"},
                                {"type": "PLAYER_LIFE_LTE", "player": "SELF", "value": 5},
                            ],
                            fixed_value_provider(5000),
                        ),
                    }
                ],
                kind="TRIGGERED",
            ),
            priority=130,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_threshold_remove_dynamic_sayaka_life"},
        ),
        TemplateRule(
            name="event.bp_remove.dynamic_madoka",
            event_filter="ON_PLAY",
            matcher=exact_text_match("『BP3000以下』の相手のフロントLのキャラを1枚選び、退場させる。自分の場に〈鹿目 まどか〉がある場合、『BP5000以下』に代わる。"),
            builder=bp_remove_with_requirements_builder_factory(
                [
                    {
                        "type": "CARD_BP_LTE_DYNAMIC",
                        "value_provider": conditional_value_provider(
                            fixed_value_provider(3000),
                            [{"type": "CONTROLLER_HAS_NAME_IN_FIELD", "value": "鹿目 まどか"}],
                            fixed_value_provider(5000),
                        ),
                    }
                ],
                kind="TRIGGERED",
            ),
            priority=130,
            template_metadata={"family": "BP_THRESHOLD_REMOVE", "variant": "bp_threshold_remove_dynamic_madoka"},
        ),
        TemplateRule(
            name="event.bp_sum_limit_remove.dynamic_energy_line",
            event_filter="ON_PLAY",
            matcher=regex_match(r"BPの合計が自分のエナジーラインのカード枚数×(\d+)以下になるように相手のフロントLのキャラを(\d+)枚まで選び、退場させる。"),
            builder=bp_sum_limit_remove_dynamic_energy_builder,
            priority=136,
            template_metadata={"family": "BP_SUM_LIMIT_REMOVE", "variant": "bp_sum_limit_remove_dynamic_energy_line"},
        ),
    )
