extends RefCounted
class_name ActionTypes

const PLAY_CARD := "PLAY_CARD"
const MOVE_CARD := "MOVE_CARD"
const ATTACK := "ATTACK"
const BLOCK := "BLOCK"
const NO_BLOCK := "NO_BLOCK"
const ACTIVATE_EFFECT := "ACTIVATE_EFFECT"
const RESOLVE_PENDING_DECISION := "RESOLVE_PENDING_DECISION"
const RESOLVE_LIFE_TRIGGER := "RESOLVE_LIFE_TRIGGER"
const ADVANCE_PHASE := "ADVANCE_PHASE"
const END_TURN := "END_TURN"
const BONUS_DRAW := "BONUS_DRAW"

const MOVE_ENERGY_TO_FRONT := "ENERGY_TO_FRONT"
const MOVE_STEP_TO_ENERGY := "STEP_TO_ENERGY"

static func is_action_type(value: String) -> bool:
	return value in [
		PLAY_CARD,
		MOVE_CARD,
		ATTACK,
		BLOCK,
		NO_BLOCK,
		ACTIVATE_EFFECT,
		RESOLVE_PENDING_DECISION,
		RESOLVE_LIFE_TRIGGER,
		ADVANCE_PHASE,
		END_TURN,
		BONUS_DRAW,
	]
